//
//  ItemDetailInteractor.swift
//  GL-Test
//
//  Created by Marcelo Perretta on 06/03/2018.
//  Copyright (c) 2018 MAWAPE. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ItemDetailBusinessLogic
{
  func doSomething(request: ItemDetail.Something.Request)
}

protocol ItemDetailDataStore
{
  //var name: String { get set }
}

class ItemDetailInteractor: ItemDetailBusinessLogic, ItemDetailDataStore
{
  var presenter: ItemDetailPresentationLogic?
  var worker: ItemDetailWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: ItemDetail.Something.Request)
  {
    worker = ItemDetailWorker()
    worker?.doSomeWork()
    
    let response = ItemDetail.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
