//
//  LoadItemsModels.swift
//  GL-Test
//
//  Created by Marcelo Perretta on 06/03/2018.
//  Copyright (c) 2018 MAWAPE. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum LoadItems
{
  // MARK: Use cases
  
  enum Data
  {
    struct Request
    {
    }
    struct Response
    {
        var items: [Item] = []
    }
    struct ViewModel
    {
        var items: [Item] = []
    }
  }
}
