//
//  LoadItemsInteractor.swift
//  GL-Test
//
//  Created by Marcelo Perretta on 06/03/2018.
//  Copyright (c) 2018 MAWAPE. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoadItemsBusinessLogic
{
  func loadItems(request: LoadItems.Data.Request)
}

protocol LoadItemsDataStore
{
  //var name: String { get set }
}

class LoadItemsInteractor: LoadItemsBusinessLogic, LoadItemsDataStore
{
  var presenter: LoadItemsPresentationLogic?
  var worker: LoadItemsWorkerProtocol = LoadItemsWorker()
  //var name: String = ""
  
  // MARK: Do something
  
  func loadItems(request: LoadItems.Data.Request)
  {
    worker.loadItemsFromServer { (result) in
        let response = LoadItems.Data.Response(items: result)
        self.presenter?.presentItems(response: response)
    }
  }
}
